# Generated by Django 4.2.13 on 2024-07-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='user_type',
            field=models.CharField(max_length=30),
        ),
    ]
