# Generated by Django 4.2.13 on 2024-07-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_name_customer_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(default='PENDING', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='status',
            field=models.CharField(default='PENDING', max_length=100, null=True),
        ),
    ]
