# Generated by Django 4.2.13 on 2024-07-17 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('image', models.FileField(null=True, upload_to='file')),
                ('amount', models.CharField(max_length=100, null=True)),
                ('bidstatus', models.CharField(default='PENDING', max_length=100, null=True)),
                ('bidStartDate', models.CharField(max_length=100, null=True)),
                ('bidEndDate', models.CharField(max_length=100, null=True)),
                ('time', models.CharField(max_length=100, null=True)),
                ('sellerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.seller')),
            ],
        ),
    ]
