# Generated by Django 4.2.13 on 2024-07-24 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_bidtable_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bidStartDate',
        ),
        migrations.AddField(
            model_name='product',
            name='customerid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.customer'),
        ),
    ]
