# Generated by Django 4.2.13 on 2024-07-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_product_bidenddate_product_customerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ssssss',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
