# Generated by Django 4.2.13 on 2024-07-25 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_product_ssssss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ssssss',
        ),
    ]
