# Generated by Django 4.2.13 on 2024-07-25 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_product_adsadfamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='adsadfamount',
        ),
    ]
