# Generated by Django 4.2.13 on 2024-07-25 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_product_adsadfamount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='time',
            new_name='paymentStatus',
        ),
    ]
